### ISSUE TITLE
MacOS JNI Errors

### ISSUE THREAD

**Issue by pomadchin** [TileDB-Inc/TileDB-Java#154]
Hello,

I'm getting the following exception trying to create a `new Context()`:

```java
tdb.TileDBUtilsSpec *** ABORTED *** (268 milliseconds)
   java.lang.UnsatisfiedLinkError: io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()J
   at io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp(Native Method)
   at io.tiledb.libtiledb.tiledb.new_tiledb_config_tpp(tiledb.java:541)
   at io.tiledb.java.api.Config.<init>(Config.java:67)
   at io.tiledb.java.api.Context.<init>(Context.java:69)
```

The interesting fact about it, is that library can be fetched via `System.loadLibrary` call, however it looks like smth else mismatches.

Local Lib versions:
* `MacOS Catalina`
* `TileDB 1.7.7`, installed via brew
* `TileDB Java 0.2.4`
* `Java 1.8`

I'm also working on trying to test it in Docker, however it looks like there is no any prebuilt docker container for Java purposes.

**Comment by gsvic** [comment]
Hi @pomadchin. How do you import TileDB-Java in your project? Do you added as an external resource from Maven Central (with gradle, mvn, sbt) or as a local jar?

**Comment by pomadchin** [comment]
@gsvic yes, it is an external dependency fetched from maven central.

**Comment by gsvic** [comment]
@pomadchin Thanks for reporting that, I'll check this out and get back to you. Could you please try the following as a temporary workaround? 

1. Remove the TileDB 1.7.7 that you installed with brew
2. Clone TileDB-Java from: https://github.com/TileDB-Inc/TileDB-Java
3. Checkout the `0.2.4` branch
3. Build the repo with `./gradlew assemble`
4. Import the local jar (`tiledb-java-0.2.4.jar`) in your project. For example, with gradle you can do you this by including something like `compile files('tiledb-java-0.2.4.jar')` as a dependency.

That should work (tested on my MacOS Catalina setup). Let us know if that works.

**Comment by pomadchin** [comment]
Thanks a lot @gsvic, the workaround perfectly works! 

I also had a chance to start a docker conatiner with the TileDB installed via conda and it also seems to work. The next step would be to try to install TileDB on macos via conda :D.

**Comment by gsvic** [comment]
Glad to hear that it works @pomadchin, thank you for the feedback!

We'll come up with some fix for the brew/conda issue and get back as soon as possible!

**Comment by pomadchin** [comment]
Will post an extra update (mb it would be useful), I only needed dylibs generated to make it work; I can use the binary pulled down from the maven central but point jvm to the `TileDB-Java/build/install/lib/` dir.

So it is definitely smth related to how C binaries are built.

**Comment by Shelnutt2** [comment]
The maven central jar does not currently support osx for the native libraries. We only upload a build with linux native libraries. We will look at getting the fat jar built for osx also, please give us a few days for this.

In the mean time, the work around is to build from source as @gsvic has mentioned. If you'd like to build TileDB-Java from source but use an installation of `libtiledb`, you can but it requires a minor tweak to your runtime.

The problem is java has a very limited set of places it looks for native libraries. Java does not observe the typical library path settings (`ld.conf`/`LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`). So when you install TileDB from conda or homebrew it won't work for java to find the library, even though other systems like python find it without issue.

The quick work around for you is to set the library path JVM argument to the location where libtiledb is installed, https://stackoverflow.com/a/2309723/11562375 .

When you build the jar locally you can also install it to the local maven repository, with `./gradlew publishMavenJavaPublicationToMavenLocal`. This will allow you to have the jar local and use it as if it was pulled from maven central. In your project you just need to include `mavenLocal()` in your repository list (if using gradle).

**Comment by pomadchin** [comment]
@Shelnutt2 ah I see; I didn't pay attention to the fact that you really put binaries into the jar! It explains the behvior.

Thanks for lots of clarifications all makes sense now. :+1:

**Comment by gsvic** [comment]
Hi @pomadchin,

We would like to let you know that we recently released TileDB-Java 0.3.0 which comes with pre-compiled OSX native libraries. Here is the link: https://search.maven.org/artifact/io.tiledb/tiledb-java/0.3.0

Now you should be able to run your Java code by just including the dependency from Maven Central.

Let us know if you face any issues.

Best,
Victor

**Comment by pomadchin** [comment]
Hi @gsvic thanks a lot! I'll try to check it this friday!

**Comment by pomadchin** [comment]
It took me a bit longer to test it out, it perfectly works now. Thanks a lot! 🎉 🎉 🎉 🎉

**Comment by gsvic** [comment]
> It took me a bit longer to test it out, it perfectly works now. Thanks a lot! 🎉 🎉 🎉 🎉

Glad to hear that it worked @pomadchin!

**Comment by mosabdullah** [comment]
Hi @gsvic, 

I came across this post as I am having problems with an Apple Silicon Mac. I have included the dependency in my gradle build as implementation("io.tiledb:tiledb-java:0.17.9"). 

According to your post above, this should include the osx native libraries, and upon checking it does. However, the following error gets thrown no matter how I try and implement this. Even generated the TileDB-Java library myself. 

Caused by: java.lang.UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'
2023-09-21T04:28:44.664685135Z 	at io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp(Native Method)
2023-09-21T04:28:44.664686760Z 	at io.tiledb.libtiledb.tiledb.new_tiledb_config_tpp(tiledb.java:660)
2023-09-21T04:28:44.664688385Z 	at io.tiledb.java.api.Config.<init>(Config.java:68)
2023-09-21T04:28:44.664690135Z 	at io.tiledb.java.api.Context.<init>(Context.java:69)

My only guess is that the libraries support intel mac versions and maybe not apple silicon, but even then it should work because of Rosetta2 installation.

Any help would be greatly appreciated. 

Thanks,

Mo
